
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormUsuarios extends javax.swing.JFrame {

    ArrayList<String> nombreList = new ArrayList<>();
    ArrayList<String> apellidoList = new ArrayList<>();
    ArrayList<String> correoList = new ArrayList<>();
    ArrayList<Integer> edadList = new ArrayList<>();
    DefaultTableModel model;
    int countIndex = 0;
    String[] column = {"Nombre", "Apellido", "Correo", "Edad"};
    
    public FormUsuarios() {
        initComponents();    
        model = new DefaultTableModel(column, 0);
        tabla.setModel(model);
        
        tabla.setDefaultEditor(Object.class, null);
        
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Registro De Usuarios");
        txtResultado.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnLimpiarH = new javax.swing.JButton();
        btnTabla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 620, 330));

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane2.setViewportView(txtResultado);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 620, 230));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 1, 37)); // NOI18N
        jLabel1.setText("Formulario De Usuarios");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, -10, 620, 120));

        jPanel3.setBackground(new java.awt.Color(250, 253, 231));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 14)); // NOI18N
        jLabel2.setText("Edad:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 14)); // NOI18N
        jLabel4.setText("Apellido:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 14)); // NOI18N
        jLabel5.setText("Correo:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));
        jPanel3.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 240, 30));
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 150, 30));
        jPanel3.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 150, 30));
        jPanel3.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 150, 30));

        btnAgregar.setBackground(new java.awt.Color(255, 255, 204));
        btnAgregar.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 90, -1));

        btnModificar.setBackground(new java.awt.Color(51, 204, 255));
        btnModificar.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        jPanel3.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(51, 255, 204));
        btnEliminar.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        jPanel3.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 100, -1));

        btnBuscar.setBackground(new java.awt.Color(255, 204, 204));
        btnBuscar.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        btnLimpiarH.setBackground(new java.awt.Color(255, 153, 153));
        btnLimpiarH.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 14)); // NOI18N
        btnLimpiarH.setText("Limpiar Historial");
        jPanel3.add(btnLimpiarH, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 170, -1));

        btnTabla.setBackground(new java.awt.Color(255, 153, 153));
        btnTabla.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 14)); // NOI18N
        btnTabla.setText("Limpiar Tabla");
        jPanel3.add(btnTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 170, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 670));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(nombreList.isEmpty()){
            JOptionPane.showMessageDialog(this, "Error: No hay registros", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }    
        
        String key = JOptionPane.showInputDialog("Ingrese el nombre o apellido: ");
            
            if(key == null || key.trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Error: Ingrese Un Nombre o Apellido Porfavor", "Error", JOptionPane.ERROR_MESSAGE);
                return;
                
            }
             boolean encontrado = false;
            
           for (int i = 0; i < nombreList.size(); i++) {
            if(nombreList.get(i).equalsIgnoreCase(key) || apellidoList.get(i).equalsIgnoreCase(key)){
                tabla.setRowSelectionInterval(i, i);
                tabla.scrollRectToVisible(tabla.getCellRect(i, 0, true));
                JOptionPane.showMessageDialog(this, "Dato: " + key + "\n"+"Encontrado En La Fila["+i+"]");
                encontrado = true;
                break;
                
            }
            
        }
           
           if(encontrado == false){
               JOptionPane.showMessageDialog(this, "Dato No Encontrado", "Info", JOptionPane.INFORMATION_MESSAGE);
               return;
           }
            
           
            
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       StringBuilder datos = new StringBuilder("\nRegistro ["+countIndex+"]\n").append("-----------------------------------------------------------------------------\n");
       
        if(txtNombre.getText().trim().isEmpty() || txtApellido.getText().trim().isEmpty() || txtCorreo.getText().trim().isEmpty() || txtEdad.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Error: Debe Ingresar Los Campos No Pueden Estar Vacios", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!txtEdad.getText().matches("\\d+")){
            JOptionPane.showMessageDialog(this, "Error: Debe Ingresar Numeros En Edad", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String correo = txtCorreo.getText().trim().toLowerCase();
        int edad = Integer.parseInt(txtEdad.getText());
        
        if(!nombre.matches("[a-zA-Z\\s]+") || !apellido.matches("[a-zA-Z\\s]+")){
            
            JOptionPane.showMessageDialog(this, "Error: Los Campos De Nombre, Apellido, Correo deben ser texto", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!correo.contains("@") || !correo.contains(".")){
            JOptionPane.showMessageDialog(this, "Error: El Correo Debe Contener @ y .");
            return;
        }
        
        if(correoList.contains(correo)){
            JOptionPane.showMessageDialog(this, "Error: El Correo Electronico -> " + correo + " ya existe.", "Dato Duplicado", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        nombreList.add(nombre);
        apellidoList.add(apellido);
        correoList.add(correo);
        edadList.add(edad);
        
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        Object[] fila = {nombre, apellido, correo, edad};
        modelo.addRow(fila);
              
        
        txtNombre.setText("");
        txtApellido.setText("");
        txtCorreo.setText("");
        txtEdad.setText("");
        
        datos.append("Nombre: " + nombre + "\n").append("Apellido: " + apellido + "\n").append("Edad: " + edad + "\n").append("Correo Electronico: " + correo + "\n").append("-----------------------------------------------------------------------------\n");  
        txtResultado.append(datos.toString());
        JOptionPane.showMessageDialog(this, "Dato["+countIndex+"] Registrado Correctamente");
        countIndex = countIndex + 1;
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiarH;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
